<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function detailproduct($id)
    {
        return $this->getEntityManager()->createQuery('SELECT product FROM AppBundle:Produit product WHERE product.id = ' . $id)->getResult();
    }
}
